// GENERATED CODE - DO NOT MODIFY MANUALLY
// **************************************************************************
// Auto generated by https://github.com/fluttercandies/assets_generator
// **************************************************************************
// ignore_for_file: constant_identifier_names

class Assets {
  const Assets._();

  /// {@macro assets_generator.assets_467141054_jpg.preview}
  static const String assets_467141054_jpg = 'assets/467141054.jpg';

  /// {@macro assets_generator.assets_avatar_jpg.preview}
  static const String assets_avatar_jpg = 'assets/avatar.jpg';

  /// {@macro assets_generator.assets_emoji_1_png.preview}
  static const String assets_emoji_1_png = 'assets/emoji/1.png';

  /// {@macro assets_generator.assets_emoji_10_png.preview}
  static const String assets_emoji_10_png = 'assets/emoji/10.png';

  /// {@macro assets_generator.assets_emoji_11_png.preview}
  static const String assets_emoji_11_png = 'assets/emoji/11.png';

  /// {@macro assets_generator.assets_emoji_12_png.preview}
  static const String assets_emoji_12_png = 'assets/emoji/12.png';

  /// {@macro assets_generator.assets_emoji_13_png.preview}
  static const String assets_emoji_13_png = 'assets/emoji/13.png';

  /// {@macro assets_generator.assets_emoji_14_png.preview}
  static const String assets_emoji_14_png = 'assets/emoji/14.png';

  /// {@macro assets_generator.assets_emoji_15_png.preview}
  static const String assets_emoji_15_png = 'assets/emoji/15.png';

  /// {@macro assets_generator.assets_emoji_16_png.preview}
  static const String assets_emoji_16_png = 'assets/emoji/16.png';

  /// {@macro assets_generator.assets_emoji_17_png.preview}
  static const String assets_emoji_17_png = 'assets/emoji/17.png';

  /// {@macro assets_generator.assets_emoji_18_png.preview}
  static const String assets_emoji_18_png = 'assets/emoji/18.png';

  /// {@macro assets_generator.assets_emoji_19_png.preview}
  static const String assets_emoji_19_png = 'assets/emoji/19.png';

  /// {@macro assets_generator.assets_emoji_2_png.preview}
  static const String assets_emoji_2_png = 'assets/emoji/2.png';

  /// {@macro assets_generator.assets_emoji_20_png.preview}
  static const String assets_emoji_20_png = 'assets/emoji/20.png';

  /// {@macro assets_generator.assets_emoji_21_png.preview}
  static const String assets_emoji_21_png = 'assets/emoji/21.png';

  /// {@macro assets_generator.assets_emoji_22_png.preview}
  static const String assets_emoji_22_png = 'assets/emoji/22.png';

  /// {@macro assets_generator.assets_emoji_23_png.preview}
  static const String assets_emoji_23_png = 'assets/emoji/23.png';

  /// {@macro assets_generator.assets_emoji_24_png.preview}
  static const String assets_emoji_24_png = 'assets/emoji/24.png';

  /// {@macro assets_generator.assets_emoji_25_png.preview}
  static const String assets_emoji_25_png = 'assets/emoji/25.png';

  /// {@macro assets_generator.assets_emoji_26_png.preview}
  static const String assets_emoji_26_png = 'assets/emoji/26.png';

  /// {@macro assets_generator.assets_emoji_27_png.preview}
  static const String assets_emoji_27_png = 'assets/emoji/27.png';

  /// {@macro assets_generator.assets_emoji_28_png.preview}
  static const String assets_emoji_28_png = 'assets/emoji/28.png';

  /// {@macro assets_generator.assets_emoji_29_png.preview}
  static const String assets_emoji_29_png = 'assets/emoji/29.png';

  /// {@macro assets_generator.assets_emoji_3_png.preview}
  static const String assets_emoji_3_png = 'assets/emoji/3.png';

  /// {@macro assets_generator.assets_emoji_30_png.preview}
  static const String assets_emoji_30_png = 'assets/emoji/30.png';

  /// {@macro assets_generator.assets_emoji_31_png.preview}
  static const String assets_emoji_31_png = 'assets/emoji/31.png';

  /// {@macro assets_generator.assets_emoji_32_png.preview}
  static const String assets_emoji_32_png = 'assets/emoji/32.png';

  /// {@macro assets_generator.assets_emoji_33_png.preview}
  static const String assets_emoji_33_png = 'assets/emoji/33.png';

  /// {@macro assets_generator.assets_emoji_34_png.preview}
  static const String assets_emoji_34_png = 'assets/emoji/34.png';

  /// {@macro assets_generator.assets_emoji_35_png.preview}
  static const String assets_emoji_35_png = 'assets/emoji/35.png';

  /// {@macro assets_generator.assets_emoji_36_png.preview}
  static const String assets_emoji_36_png = 'assets/emoji/36.png';

  /// {@macro assets_generator.assets_emoji_37_png.preview}
  static const String assets_emoji_37_png = 'assets/emoji/37.png';

  /// {@macro assets_generator.assets_emoji_38_png.preview}
  static const String assets_emoji_38_png = 'assets/emoji/38.png';

  /// {@macro assets_generator.assets_emoji_39_png.preview}
  static const String assets_emoji_39_png = 'assets/emoji/39.png';

  /// {@macro assets_generator.assets_emoji_4_png.preview}
  static const String assets_emoji_4_png = 'assets/emoji/4.png';

  /// {@macro assets_generator.assets_emoji_40_png.preview}
  static const String assets_emoji_40_png = 'assets/emoji/40.png';

  /// {@macro assets_generator.assets_emoji_41_png.preview}
  static const String assets_emoji_41_png = 'assets/emoji/41.png';

  /// {@macro assets_generator.assets_emoji_42_png.preview}
  static const String assets_emoji_42_png = 'assets/emoji/42.png';

  /// {@macro assets_generator.assets_emoji_43_png.preview}
  static const String assets_emoji_43_png = 'assets/emoji/43.png';

  /// {@macro assets_generator.assets_emoji_44_png.preview}
  static const String assets_emoji_44_png = 'assets/emoji/44.png';

  /// {@macro assets_generator.assets_emoji_45_png.preview}
  static const String assets_emoji_45_png = 'assets/emoji/45.png';

  /// {@macro assets_generator.assets_emoji_46_png.preview}
  static const String assets_emoji_46_png = 'assets/emoji/46.png';

  /// {@macro assets_generator.assets_emoji_47_png.preview}
  static const String assets_emoji_47_png = 'assets/emoji/47.png';

  /// {@macro assets_generator.assets_emoji_48_png.preview}
  static const String assets_emoji_48_png = 'assets/emoji/48.png';

  /// {@macro assets_generator.assets_emoji_5_png.preview}
  static const String assets_emoji_5_png = 'assets/emoji/5.png';

  /// {@macro assets_generator.assets_emoji_6_png.preview}
  static const String assets_emoji_6_png = 'assets/emoji/6.png';

  /// {@macro assets_generator.assets_emoji_7_png.preview}
  static const String assets_emoji_7_png = 'assets/emoji/7.png';

  /// {@macro assets_generator.assets_emoji_8_png.preview}
  static const String assets_emoji_8_png = 'assets/emoji/8.png';

  /// {@macro assets_generator.assets_emoji_9_png.preview}
  static const String assets_emoji_9_png = 'assets/emoji/9.png';
}
