// GENERATED CODE - DO NOT MODIFY MANUALLY
// **************************************************************************
// Auto generated by https://github.com/fluttercandies/ff_annotation_route
// **************************************************************************

import 'package:flutter/widgets.dart';

import 'demo/custom_indicator_demo.dart';
import 'demo/grid_view_demo.dart';
import 'demo/list_view_demo.dart';
import 'demo/main_page.dart';
import 'demo/multiple_sliver_demo.dart';
import 'demo/nested_scroll_view_demo.dart';
import 'demo/sliver_grid_demo.dart';
import 'demo/sliver_list_demo.dart';
import 'demo/waterfall_flow_demo.dart';

// ignore_for_file: argument_type_not_assignable
RouteResult getRouteResult({String name, Map<String, dynamic> arguments}) {
  switch (name) {
    case 'fluttercandies://CustomIndicatorDemo':
      return RouteResult(
        name: name,
        widget: CustomIndicatorDemo(),
        routeName: 'CustomIndicator',
        description:
            'Show how to build loading more list with custom indicator quickly',
      );
    case 'fluttercandies://GridViewDemo':
      return RouteResult(
        name: name,
        widget: GridViewDemo(),
        routeName: 'GridView',
        description: 'Show how to build loading more GridView quickly',
      );
    case 'fluttercandies://ListViewDemo':
      return RouteResult(
        name: name,
        widget: ListViewDemo(),
        routeName: 'ListView',
        description: 'Show how to build loading more ListView quickly',
      );
    case 'fluttercandies://MultipleSliverDemo':
      return RouteResult(
        name: name,
        widget: MultipleSliverDemo(),
        routeName: 'MultipleSliver',
        description:
            'Show how to build loading more multiple sliver list quickly',
      );
    case 'fluttercandies://NestedScrollViewDemo':
      return RouteResult(
        name: name,
        widget: NestedScrollViewDemo(),
        routeName: 'NestedScrollView',
        description:
            'Show how to build loading more list in NestedScrollView quickly',
      );
    case 'fluttercandies://SliverGridDemo':
      return RouteResult(
        name: name,
        widget: SliverGridDemo(),
        routeName: 'SliverGrid',
        description: 'Show how to build loading more SilverGird quickly',
      );
    case 'fluttercandies://SliverListDemo':
      return RouteResult(
        name: name,
        widget: SliverListDemo(),
        routeName: 'SliverList',
        description: 'Show how to build loading more SliverList quickly',
      );
    case 'fluttercandies://WaterfallFlowDemo':
      return RouteResult(
        name: name,
        widget: WaterfallFlowDemo(),
        routeName: 'WaterfallFlow',
        description: 'Show how to build loading more WaterfallFlow quickly',
      );
    case 'fluttercandies://mainpage':
      return RouteResult(
        name: name,
        widget: MainPage(),
        routeName: 'MainPage',
      );
    default:
      return const RouteResult(name: 'flutterCandies://notfound');
  }
}

class RouteResult {
  const RouteResult({
    @required this.name,
    this.widget,
    this.showStatusBar = true,
    this.routeName = '',
    this.pageRouteType,
    this.description = '',
    this.exts,
  });

  /// The name of the route (e.g., "/settings").
  ///
  /// If null, the route is anonymous.
  final String name;

  /// The Widget return base on route
  final Widget widget;

  /// Whether show this route with status bar.
  final bool showStatusBar;

  /// The route name to track page
  final String routeName;

  /// The type of page route
  final PageRouteType pageRouteType;

  /// The description of route
  final String description;

  /// The extend arguments
  final Map<String, dynamic> exts;
}

enum PageRouteType {
  material,
  cupertino,
  transparent,
}
