// GENERATED CODE - DO NOT MODIFY MANUALLY
// **************************************************************************
// Auto generated by https://github.com/fluttercandies/ff_annotation_route
// **************************************************************************
// fast mode: true
// version: 10.0.10
// **************************************************************************
// ignore_for_file: prefer_const_literals_to_create_immutables,unused_local_variable,unused_import,unnecessary_import,unused_shown_name,implementation_imports,duplicate_import
/// The routeNames auto generated by https://github.com/fluttercandies/ff_annotation_route
const List<String> routeNames = <String>[
  'fluttercandies://CustomIndicatorDemo',
  'fluttercandies://GridViewDemo',
  'fluttercandies://ListViewDemo',
  'fluttercandies://MultipleSliverDemo',
  'fluttercandies://MultipleSliverDemo1',
  'fluttercandies://NestedScrollViewDemo',
  'fluttercandies://SliverCenterDemo',
  'fluttercandies://SliverGridDemo',
  'fluttercandies://SliverListDemo',
  'fluttercandies://WaterfallFlowDemo',
  'fluttercandies://demogrouppage',
  'fluttercandies://mainpage',
];

/// The routes auto generated by https://github.com/fluttercandies/ff_annotation_route
class Routes {
  const Routes._();

  /// 'Show how to build loading more list with custom indicator quickly'
  ///
  /// [name] : 'fluttercandies://CustomIndicatorDemo'
  ///
  /// [routeName] : 'CustomIndicator'
  ///
  /// [description] : 'Show how to build loading more list with custom indicator quickly'
  ///
  /// [exts] : {'group': 'Simple', 'order': 2}
  static const String fluttercandiesCustomIndicatorDemo =
      'fluttercandies://CustomIndicatorDemo';

  /// 'Show how to build loading more GridView quickly'
  ///
  /// [name] : 'fluttercandies://GridViewDemo'
  ///
  /// [routeName] : 'GridView'
  ///
  /// [description] : 'Show how to build loading more GridView quickly'
  ///
  /// [exts] : {'group': 'Simple', 'order': 1}
  static const String fluttercandiesGridViewDemo =
      'fluttercandies://GridViewDemo';

  /// 'Show how to build loading more ListView quickly'
  ///
  /// [name] : 'fluttercandies://ListViewDemo'
  ///
  /// [routeName] : 'ListView'
  ///
  /// [description] : 'Show how to build loading more ListView quickly'
  ///
  /// [exts] : {'group': 'Simple', 'order': 0}
  static const String fluttercandiesListViewDemo =
      'fluttercandies://ListViewDemo';

  /// 'Show how to build loading more multiple sliver list quickly'
  ///
  /// [name] : 'fluttercandies://MultipleSliverDemo'
  ///
  /// [routeName] : 'MultipleSliver'
  ///
  /// [description] : 'Show how to build loading more multiple sliver list quickly'
  ///
  /// [exts] : {'group': 'Simple', 'order': 5}
  static const String fluttercandiesMultipleSliverDemo =
      'fluttercandies://MultipleSliverDemo';

  /// 'Show how to build loading more multiple sliver list quickly, and support LoadingMoreCustomScrollView.slivers are not a direct LoadingMoreSliverList'
  ///
  /// [name] : 'fluttercandies://MultipleSliverDemo1'
  ///
  /// [routeName] : 'MultipleSliver1'
  ///
  /// [description] : 'Show how to build loading more multiple sliver list quickly, and support LoadingMoreCustomScrollView.slivers are not a direct LoadingMoreSliverList'
  ///
  /// [exts] : {'group': 'Simple', 'order': 7}
  static const String fluttercandiesMultipleSliverDemo1 =
      'fluttercandies://MultipleSliverDemo1';

  /// 'Show how to build loading more list in NestedScrollView quickly'
  ///
  /// [name] : 'fluttercandies://NestedScrollViewDemo'
  ///
  /// [routeName] : 'NestedScrollView'
  ///
  /// [description] : 'Show how to build loading more list in NestedScrollView quickly'
  ///
  /// [exts] : {'group': 'Complex', 'order': 1}
  static const String fluttercandiesNestedScrollViewDemo =
      'fluttercandies://NestedScrollViewDemo';

  /// 'Show how to use LoadingMoreCustomScrollView center sliver'
  ///
  /// [name] : 'fluttercandies://SliverCenterDemo'
  ///
  /// [routeName] : 'SliverCenter'
  ///
  /// [description] : 'Show how to use LoadingMoreCustomScrollView center sliver'
  ///
  /// [exts] : {'group': 'Simple', 'order': 6}
  static const String fluttercandiesSliverCenterDemo =
      'fluttercandies://SliverCenterDemo';

  /// 'Show how to build loading more SilverGird quickly'
  ///
  /// [name] : 'fluttercandies://SliverGridDemo'
  ///
  /// [routeName] : 'SliverGrid'
  ///
  /// [description] : 'Show how to build loading more SilverGird quickly'
  ///
  /// [exts] : {'group': 'Simple', 'order': 4}
  static const String fluttercandiesSliverGridDemo =
      'fluttercandies://SliverGridDemo';

  /// 'Show how to build loading more SliverList quickly'
  ///
  /// [name] : 'fluttercandies://SliverListDemo'
  ///
  /// [routeName] : 'SliverList'
  ///
  /// [description] : 'Show how to build loading more SliverList quickly'
  ///
  /// [exts] : {'group': 'Simple', 'order': 3}
  static const String fluttercandiesSliverListDemo =
      'fluttercandies://SliverListDemo';

  /// 'Show how to build loading more WaterfallFlow quickly'
  ///
  /// [name] : 'fluttercandies://WaterfallFlowDemo'
  ///
  /// [routeName] : 'WaterfallFlow'
  ///
  /// [description] : 'Show how to build loading more WaterfallFlow quickly'
  ///
  /// [exts] : {'group': 'Complex', 'order': 0}
  static const String fluttercandiesWaterfallFlowDemo =
      'fluttercandies://WaterfallFlowDemo';

  /// 'DemoGroupPage'
  ///
  /// [name] : 'fluttercandies://demogrouppage'
  ///
  /// [routeName] : 'DemoGroupPage'
  ///
  /// [constructors] :
  ///
  /// DemoGroupPage : [MapEntry<String, List<DemoRouteResult>>(required) keyValue]
  static const String fluttercandiesDemogrouppage =
      'fluttercandies://demogrouppage';

  /// 'MainPage'
  ///
  /// [name] : 'fluttercandies://mainpage'
  ///
  /// [routeName] : 'MainPage'
  ///
  /// [constructors] :
  ///
  /// MainPage : []
  static const String fluttercandiesMainpage = 'fluttercandies://mainpage';
}
